# Generated by Django 3.2 on 2022-12-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_ref',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
