# Generated by Django 3.2 on 2022-12-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_sold_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_in',
            field=models.CharField(choices=[('single', 'Single'), ('basket', 'Basket')], max_length=10, null=True),
        ),
    ]
