# Generated by Django 3.2 on 2022-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_sold_in'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_in',
            field=models.CharField(choices=[('singles', 'Singles'), ('baskets', 'Baskets')], max_length=10, null=True),
        ),
    ]
