# Generated by Django 3.2 on 2022-12-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_sold_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='former_price',
            field=models.DecimalField(decimal_places=2, max_digits=9, null=True),
        ),
    ]
