# Generated by Django 3.2 on 2022-12-29 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_average_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
